// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3QGpAQ2vs6YcE3HQ0BknpptNyBV05_vI',
    appId: '1:941163283759:web:f657ec72211911d7658dda',
    messagingSenderId: '941163283759',
    projectId: 'rdpguestbook-master',
    authDomain: 'rdpguestbook-master.firebaseapp.com',
    storageBucket: 'rdpguestbook-master.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmp6lHFJoNys--QNNRuuCPSXflVfLCGrE',
    appId: '1:941163283759:android:949252c03a293c0a658dda',
    messagingSenderId: '941163283759',
    projectId: 'rdpguestbook-master',
    storageBucket: 'rdpguestbook-master.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCu505QSxjQ-Wo_FnfSnG6VurKHmc0ukQ',
    appId: '1:941163283759:ios:ff4eeec393d75d6d658dda',
    messagingSenderId: '941163283759',
    projectId: 'rdpguestbook-master',
    storageBucket: 'rdpguestbook-master.appspot.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCu505QSxjQ-Wo_FnfSnG6VurKHmc0ukQ',
    appId: '1:941163283759:ios:9ce494753303d3e8658dda',
    messagingSenderId: '941163283759',
    projectId: 'rdpguestbook-master',
    storageBucket: 'rdpguestbook-master.appspot.com',
    iosBundleId: 'com.example.flutterProject.RunnerTests',
  );
}
